init commit
jamstackpb/informatorpb pull request #40
Opened 2022-02-23 22:11 UTC by ghosttly

Narazie zrobione tylko zaciąganie wszystkich danych kół naukowych i absolwentów oraz prosty szkielet ich osadzenia. Trochę pozmieniałem i mam nadzieję, że nikt się nie obrazi ;p Lifting wyglądu zrobię do końca tygodnia z powodu braku czasu(praca)

2022-02-23 22:12 UTC, ghosttly commented
Przy konflikcie ode mnie zostaje 
import { AddPage, AddPagesWithContent, AddPlainPage } from '../atoms/AddPage';

2022-02-28 20:36 UTC, SMATEO49 commented on apps/flipbook/src/components/organism/flipbook.tsx
> + main
main wywala błąd (literówka?)

2022-02-28 20:39 UTC, SMATEO49 requested changes
"main" usunąć pod importem w flipbook.tsx 
reszta spoko (są YT elementy)

2022-03-01 16:41 UTC, SMATEO49 approved these changes

2022-03-03 15:45 UTC, merged